name: Build X86 Foxy Deb Package

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
    job1:
        name: Build
        runs-on: ubuntu-18.04
        steps:
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ap-southeast-2
          - name: Run CodeBuild
            uses: aws-actions/aws-codebuild-run-build@v1.0.3
            with:
              project-name: image_processing_utils-x86-foxy