local_waypoint_server:
  ros__parameters:
    goal_pose_topic: "/move_base_simple/goal"
    obstacle_scan_topic : "/perception/pointcloud_to_laserscan_node/output"
    planning_frame_id : "map"
    robot_width : 3.0
    num_candidates : 16
    sampling_interval : 1.5
    sampling_offset : 1.3
    margin : 0.5
